version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=sqlite:///./data/face_auth.db
    volumes:
      - ./data:/app/data